sudo: required
services:
  - docker

before_install:
- echo "before_install_qpal"
#   - docker build -t rjai/react-test -f ./client/Dockerfile.dev ./client

script:
  - echo "script_qpal_section"
#   - docker run -e CI=true rjai/react-test npm test 

after_success:
#   - docker build -t rjai/multi-client ./client
#   - docker build -t rjai/multi-nginx ./nginx
#   - docker build -t rjai/multi-server ./server
#   - docker build -t rjai/multi-worker ./worker
#   # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#   # take those images and push them to docker hub
#   - docker push rjai/multi-client
#   - docker push rjai/multi-nginx
#   - docker push rjai/multi-server
#   - docker push rjai/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'multidocker-Env'
  bucket_name: 'elasticbeanstalk-us-east-2-366154563310'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY